version: "3.8"

services: 
    data_base:
        image: mysql:8.0
        container_name: mysql_8
        env_file: .env
        volumes: 
            - ./db:/var/lib/mysql
        

    server:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - 3000:3000
        container_name: node
        volumes: 
            - .:/app
            - '/app/node_modules'
        links: 
            - data_base
        depends_on: 
            - data_base